reviews:
  profile: "chill"
  poem: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches: ["master"]
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  finishing_touches:
    docstrings:
      enabled: true
