apiVersion: batch/v1
kind: Job
metadata:
  name: noobaa-analyze-network
  labels:
    app: noobaa
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: noobaa-analyze-network
        image: NOOBAA_CORE_IMAGE_PLACEHOLDER
        env:
            - name: CONTAINER_PLATFORM
              value: KUBERNETES  
        #   - name: RESOURCE_NAME
        #   - name: BUCKET
        #   - name: ENDPOINT
        #   - name: REGION
        #   - name: S3_SIGNATURE_VERSION
        #   - name: HTTP_PROXY
        #   - name: HTTPS_PROXY
        #   - name: NO_PROXY
        #   - name: NODE_EXTRA_CA_CERTS
        command: 
            - /bin/bash
            - -c
            - "cd /root/node_modules/noobaa-core/; node ./src/tools/diagnostics/analyze_network.js"
      restartPolicy: Never
      serviceAccountName: noobaa
