apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: noobaa
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
readOnlyRootFilesystem: true
