apiVersion: v1
kind: Service
metadata:
  name: warp
  labels:
    app: warp
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 7761
      name: warp
  selector:
    app: warp