apiVersion: v1
kind: ConfigMap
metadata:
  name: noobaa-postgres-config
  labels:
    app: noobaa
data:
  noobaa-postgres.conf: |
    # disable huge_pages trial
    # see https://bugzilla.redhat.com/show_bug.cgi?id=1946792
    huge_pages = off

    # postgres tuning
    max_connections = 600
    shared_buffers = 1GB
    effective_cache_size = 3GB
    maintenance_work_mem = 256MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 300
    work_mem = 1747kB
    min_wal_size = 2GB
    max_wal_size = 8GB
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = all
