apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: noobaa-mgmt-service-monitor
  labels:
    app: noobaa
spec:
  endpoints:
  - port: mgmt-https
    path: /metrics/web_server
    scheme: https
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ready]
      action: keep
      regex: "true"
  - port: mgmt-https
    path: /metrics/hosted_agents
    scheme: https
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ready]
      action: keep
      regex: "true"
  namespaceSelector: {}
  selector:
    matchLabels:
      noobaa-mgmt-svc: "true"
