apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: noobaa-s3-service-monitor
  labels:
    app: noobaa
spec:
  endpoints:
  - port: metrics
    path: /
    authorization:
      type: 'Bearer'
      credentials:
        name: metrics-auth-secret
        key: metrics_token
  namespaceSelector: {}
  selector:
    matchLabels:
      noobaa-s3-svc: "true"
