apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: noobaa-bg-workers-service-monitor
  labels:
    app: noobaa
spec:
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ready]
      action: keep
      regex: "true"
  namespaceSelector: {}
  selector:
    matchLabels:
      noobaa-bg-workers-svc: "true"
