apiVersion: v1
kind: Service
metadata:
  name: SYSNAME-bg-workers
  labels:
    app: noobaa
    noobaa-bg-workers-svc: "true"
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: noobaa-bg-workers-serving-cert
    service.alpha.openshift.io/serving-cert-secret-name: noobaa-bg-workers-serving-cert
spec:
  type: ClusterIP
  selector:
    noobaa-bg-workers: SYSNAME
  ports:
    - port: 8445
      name: bg-https
      targetPort: 8445
    - port: 7002
      name: metrics
      targetPort: 7002
