apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-service
  labels:
    app: noobaa
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    noobaa-operator: deployment
