apiVersion: v1
kind: Service
metadata:
  name: sts
  labels:
    app: noobaa
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: 'noobaa-sts-serving-cert'
    service.alpha.openshift.io/serving-cert-secret-name: 'noobaa-sts-serving-cert'
spec:
  type: LoadBalancer
  selector:
    noobaa-s3: SYSNAME
  ports:
    - port: 443
      targetPort: 7443
      name: sts-https

